-- Run this SQL in your Supabase SQL Editor to create the tables

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL, -- 'super-admin', 'admin', 'teacher'
  name TEXT NOT NULL,
  temp_password TEXT,
  assigned_class_id BIGINT
);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL, -- e.g., '2024/2025'
  is_current BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL, -- '1st Term', '2nd Term', '3rd Term'
  is_current BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL, -- 'Creche', 'Nursery 1', 'Primary 1'
  level TEXT NOT NULL -- 'creche', 'nursery', 'primary'
);

CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  class_id BIGINT REFERENCES classes(id)
);

CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admission_number TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  class_id BIGINT REFERENCES classes(id),
  pin TEXT UNIQUE NOT NULL,
  gender TEXT,
  passport TEXT
);

CREATE TABLE IF NOT EXISTS scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id),
  subject_id BIGINT NOT NULL REFERENCES subjects(id),
  session_id BIGINT NOT NULL REFERENCES sessions(id),
  term_id BIGINT NOT NULL REFERENCES terms(id),
  ca1 REAL DEFAULT 0,
  ca2 REAL DEFAULT 0,
  ca3 REAL DEFAULT 0,
  exam REAL DEFAULT 0,
  total REAL GENERATED ALWAYS AS (ca1 + ca2 + ca3 + exam) STORED,
  grade TEXT,
  remark TEXT,
  UNIQUE(student_id, subject_id, session_id, term_id)
);

CREATE TABLE IF NOT EXISTS admissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fullname TEXT NOT NULL,
  gender TEXT NOT NULL,
  dob TEXT NOT NULL,
  nationality TEXT NOT NULL,
  state TEXT NOT NULL,
  lga TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  former_school TEXT,
  former_class TEXT,
  class_applying_for BIGINT REFERENCES classes(id),
  passport TEXT, -- base64
  result TEXT, -- base64
  status TEXT DEFAULT 'pending', -- pending, approved, rejected
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_report_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id),
  session_id BIGINT NOT NULL REFERENCES sessions(id),
  term_id BIGINT NOT NULL REFERENCES terms(id),
  teacher_remark TEXT,
  head_teacher_signature TEXT, -- base64
  UNIQUE(student_id, session_id, term_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id),
  class_id BIGINT NOT NULL REFERENCES classes(id),
  session_id BIGINT NOT NULL REFERENCES sessions(id),
  term_id BIGINT NOT NULL REFERENCES terms(id),
  date DATE NOT NULL, -- YYYY-MM-DD
  status TEXT NOT NULL, -- 'present', 'absent', 'late'
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_id, date)
);

-- Add foreign key for users assigned_class_id
ALTER TABLE users ADD CONSTRAINT fk_users_classes FOREIGN KEY (assigned_class_id) REFERENCES classes(id);

-- Seed default users (Password: password123)
-- Using the hash $2b$10$J0ZzMz/auiRQ5CxU7RV1yOogxFLqFPBkF6TddMM6RA.EFGrTGkmYC which was verified to work for 'password123'
INSERT INTO users (username, password_hash, role, name) VALUES 
('admin', '$2b$10$J0ZzMz/auiRQ5CxU7RV1yOogxFLqFPBkF6TddMM6RA.EFGrTGkmYC', 'super-admin', 'Super Admin'),
('school-admin', '$2b$10$J0ZzMz/auiRQ5CxU7RV1yOogxFLqFPBkF6TddMM6RA.EFGrTGkmYC', 'admin', 'School Admin'),
('teacher', '$2b$10$J0ZzMz/auiRQ5CxU7RV1yOogxFLqFPBkF6TddMM6RA.EFGrTGkmYC', 'teacher', 'Class Teacher')
ON CONFLICT (username) DO NOTHING;
